//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Engineers_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_CState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PE_CState()
        {
            this.PE_CCity = new HashSet<PE_CCity>();
        }
    
        public int Id { get; set; }
        public int Id_Country { get; set; }
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PE_CCity> PE_CCity { get; set; }
        public virtual PE_CCountry PE_CCountry { get; set; }
    }
}
