//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Engineers_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PE_User()
        {
            this.PE_UserLocation = new HashSet<PE_UserLocation>();
        }
    
        public int Id { get; set; }
        public string Id_Honeywell { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Department { get; set; }
        public Nullable<int> Id_JobTitle { get; set; }
        public Nullable<int> Id_ApplicationRole { get; set; }
        public Nullable<int> Id_ImmediateSuperior { get; set; }
        public byte[] Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    
        public virtual PE_CApplicationRole PE_CApplicationRole { get; set; }
        public virtual PE_CDepartment PE_CDepartment { get; set; }
        public virtual PE_CJobTitle PE_CJobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PE_UserLocation> PE_UserLocation { get; set; }
    }
}
