//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Engineers_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_UserLocation
    {
        public int Id_UserLocation { get; set; }
        public int Id_User { get; set; }
        public int Id_City { get; set; }
    
        public virtual PE_CCity PE_CCity { get; set; }
        public virtual PE_User PE_User { get; set; }
    }
}
